theme: jekyll-theme-cayman
title: Adam Bourg's Development Blog
description: A blog about Javascript, industry, careers and all things web development
show_downloads: false
feed:
  excerpt_only: false
paginate: 20
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-sitemap
google_analytics: UA-5394820-3
