theme: jekyll-theme-cayman
title: Adam Bourg's Development Blog
description: Ramblings from an ADHD brain that sometimes feature something about software
show_downloads: false
feed:
  excerpt_only: false
paginate: 20
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-sitemap
google_analytics: UA-5394820-3
